#!/usr/bin/env python

import sys
import product


def process_args():

    if len(sys.argv) < 3:
        print ("USAGE: ")
        print ("\tProduct:")
        print ("\t\t./dhs product create # This will process all the products.")
        print ("\t\t./dhs product create <product_name> # This will process the specified product.")
        return False

    if sys.argv[1] == "product" and sys.argv[2] == "create":
        if len(sys.argv) == 4:
            product.handle_create_specific_product(sys.argv[3])
        else:
            product.handle_create_all()



if __name__ == "__main__":

    process_args()
